// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARleGpH57GE35M0yUDp0s3wWgNU-KfCCU',
    appId: '1:493081794788:android:9f0ba9daf8d813355fb4f1',
    messagingSenderId: '493081794788',
    projectId: 'book-bucket-ae60c',
    databaseURL: 'https://book-bucket-ae60c-default-rtdb.firebaseio.com',
    storageBucket: 'book-bucket-ae60c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_26dCmK_Jtfxv0Z9__ExVq1KBeLZaG_o',
    appId: '1:493081794788:ios:9c3445fc4f9f01ca5fb4f1',
    messagingSenderId: '493081794788',
    projectId: 'book-bucket-ae60c',
    databaseURL: 'https://book-bucket-ae60c-default-rtdb.firebaseio.com',
    storageBucket: 'book-bucket-ae60c.firebasestorage.app',
    androidClientId: '493081794788-mdgg32e7sj0fpj8bkg19e0kpoup52nfr.apps.googleusercontent.com',
    iosClientId: '493081794788-iosfktcrl2bsbk67rlms5jcgr34831hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookbucketdemoo',
  );
}
